<p><strong>Opacak Gruppe</strong></p>
<p>  Datenschutz</p>
<p><strong>Verantwortliche  Stelle</strong><br>
    Verantwortliche Stelle für die Erhebung,  Verarbeitung und Nutzung Ihrer personenbezogenen Daten im Sinne des  Bundesdatenschutzgesetzes (BDSG) ist:<br>
    Opacak Gruppe, Mario Opacak und Tomislav  Opacak, Hans-Cornelius-Strasse 4, 82166 Gräfelfing, Deutschland/Germany.<br>
    Sofern Sie der Erhebung, Verarbeitung oder  Nutzung Ihrer Daten durch solarise gemäß den datenschutzrechtlichen  Bestimmungen insgesamt oder für einzelne Maßnahmen widersprechen möchten,  richten Sie Ihren Widerspruch per Brief an folgende Kontaktdaten: Opacak Gruppe,  Mario Opacak und Tomislav Opacak, Hans-Cornelius-Strasse 4, 82166 Gräfelfing,  Deutschland/Germany.<br>
    Wir legen größten Wert auf den Schutz Ihrer  Daten und die Wahrung Ihrer Privatsphäre. Nachstehend informieren wir Sie  deshalb über die Erhebung und Verwendung persönlicher Daten bei Nutzung unserer  Webseite.<br>
    <br>
    <strong>Erheben,  Speichern &amp; Verwenden personenbezogener Daten</strong><br>
    Bei dem Besuch unserer Website erheben,  verwenden und speichern wir Ihre personenbezogenen Daten. Personenbezogene  Daten sind nach § 3 Abs. 1 BDSG Einzelangaben über persönliche oder sachliche  Verhältnisse einer bestimmten oder bestimmbaren natürlichen Person  (Betroffener).<br>
    <br>
    <strong>Datenerhebung  unter strenger Beachtung der Gesetze</strong><br>
    Bei dem Besuch unserer Website erheben,  verwenden und speichern wir Ihre personenbezogenen Daten. Personenbezogene  Daten sind nach § 3 Abs. 1 BDSG Einzelangaben über persönliche oder sachliche  Verhältnisse einer bestimmten oder bestimmbaren natürlichen Person  (Betroffener).<br>
    <br>
    <strong>Newsletter</strong><br>
    Wir nutzen Ihre E-Mail-Adresse unabhängig von  der Vertragsabwicklung ausschließlich für eigene Werbezwecke zum  Newsletterversand, sofern Sie dem ausdrücklich zugestimmt haben. Sie können den  Newsletter jederzeit unter Nutzung des entsprechenden Links im Newsletter oder  durch Nachricht an uns abbestellen. Die Kontaktdaten hierzu finden Sie in  unserem Impressum. Ihre E-Mail-Adresse wird danach umgehend gelöscht.<br>
    <br>
    <strong>Cookies</strong><br>
    Unsere Internetseite verwendet an mehreren  Stellen so genannte Cookies. &bdquo;Cookies&ldquo; sind kleine Textdateien, die auf Ihrem  Rechner abgelegt werden und die Ihr Browser speichert. Sie dienen dazu, unser  Angebot nutzerfreundlicher, effektiver und sicherer zu machen. Des Weiteren  ermöglichen Cookies unseren Systemen, Ihren Browser zu erkennen und Ihnen  Services anzubieten. Cookies enthalten keine personenbezogenen Daten. Sie haben  die Möglichkeit, das Abspeichern von Cookies auf Ihrem Rechner durch  entsprechende Einstellungen in Ihrem Browser zu verhindern. Hierdurch könnte  allerdings der Funktionsumfang unseres Angebotes eingeschränkt werden.<br>
    <br>
    <strong>Google-Analytics</strong><br>
    Diese Website benutzt Google Analytics, einen  Webanalysedienst der Google Inc. (&bdquo;Google&ldquo;). Google Analytics verwendet sog.  &bdquo;Cookies&ldquo;, Textdateien, die auf Ihrem Computer gespeichert werden und die eine  Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie  erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel  an einen Server von Google in den USA übertragen und dort gespeichert. Im Falle  der Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse  von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in  anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum  zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server  von Google in den USA übertragen und dort gekürzt. Die IP-Anonymisierung ist  auf dieser Website aktiv. Im Auftrag des Betreibers dieser Website wird Google  diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um  Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der  Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber  dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem  Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google  zusammengeführt. Sie können die Speicherung der Cookies durch eine  entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie  jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche  Funktionen dieser Website vollumfänglich werden nutzen können. Sie können  darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre  Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie  die Verarbeitung dieser Daten durch Google verhindern, indem Sie das unter dem  folgenden Link verfügbare Browser-Plugin herunterladen und installieren:  http://tools.google.com/dlpage/gaoptout?hl=de<br>
    <br>
    <strong>Verwendung  von Social Plugin</strong><br>
    Diese Website benutzt Social Media Plugins  folgender Services:<br>
    – &bdquo;Facebook-I-Like&ldquo;  bzw. &bdquo;Facebook-Gefällt-mir&ldquo;, betrieben von: Facebook Inc., 1601 S. California  Ave, Palo Alto, CA 94304, United States<br>
    – &bdquo;Twitter&rdquo;: betrieben  von: Twitter, Inc., 795 Folsom St., Suite 600, San Francisco, CA 94107, United  States<br>
    Bei diesen Social Medial Plugins handelt es  sich um von den vorgenannten Social-Media-Services entwickelte und zur  Verfügung gestellte Software, die den automatisierten Datenaustausch zwischen  der Website und den Social-Media-Services ermöglicht. So können unter anderem  Daten von einem der vorgenannten Social-Media-Services dynamisch auf die  Website übertragen werden. Gleichzeitig können auch Daten der Nutzer dieser  Website zum Social-Media-Service übertragen werden, u.a. die IP-Adresse. Die  Verwendung solcher Social Plugins erkennen Sie an den besonders  gekennzeichneten Schaltflächen. Bereits beim Anzeigen bzw. Laden der Website  können personenbezogene Daten mit dem jeweiligen Social-Media-Service  ausgetauscht werden. Nutzer haben in diesen Fällen die Möglichkeit, diesen  Datenaustausch ggf. durch Änderung in den Einstellungen ihres Benutzerkontos  auf der Website des jeweiligen Social-Media-Services abzulehnen.<br>
    Die Verwendung des Facebook-Plugins auf der  Website erkennen Sie durch das Facebook-Symbol (weißes F auf blauer Kachel bzw.  &bdquo;Daumen-hoch-Symbol&ldquo;) auf einer entsprechenden Schaltfläche. Die Verwendung des  Twitter-Plugins auf der Website erkennen Sie durch eine Anzeige der  Twitter-Logos (weißes &bdquo;t&ldquo; auf blauem Grund bzw. blauer Vogel) auf der  entsprechenden Schaltfläche. Durch den Klick auf eine dieser Schaltflächen  stimmen Sie der Nutzung dieses Plugins und damit auch der Weitergabe von  personenbezogenen Daten an den jeweiligen Social-Media-Service zu. Auf die Art  und den Umfang der dabei übertragenen Daten sowie über deren weitere Verarbeitung  haben wir keinen Einfluss. Nach unserem aktuellen Kenntnisstand wird der  jeweilige Social-Media-Service dabei über ihre IP-Adresse und über die das  Plugin nutzende Website informiert. Sofern Sie gleichzeitig auf der  entsprechenden Social-Media-Service-Plattform eingeloggt sind, können die  Informationen unmittelbar Ihrem Nutzerprofil zugeordnet werden. Möchten Sie  eine solche Sammlung von Profilinformationen vermeiden, sollten Sie sich aus  der jeweiligen Social-Media-Service-Plattform ausloggen.<br>
    Weitere Informationen von Facebook zum Umgang  mit dem entsprechenden Plugin und dem entsprechenden Social-Media-Service  erhalten Sie auf: <a href="http://developers.facebook.com/plugins">http://developers.facebook.com/plugins</a>.  Weitere Informationen von Facebook über die sog. Datenverwendungsrichtlinien  erhalten Sie auf: <a href="http://www.facebook.com/about/privacy">http://www.facebook.com/about/privacy</a>.<br>
    Weitere Informationen von Twitter zum Umgang  mit diesem Plugin und dem entsprechenden Social-Media-Service erhalten Sie auf <a href="https://twitter.com/logo">https://twitter.com/logo</a>. Weitere  Informationen von Twitter über ihre Datenschutzrichtlinie erhalten Sie auf: <a href="https://twitter.com/privacy">https://twitter.com/privacy</a>.<br>
    <br>
    <strong>Auskunft</strong><br>
    Sie haben jederzeit das Recht auf  unentgeltliche Auskunft über Ihre gespeicherten Daten sowie das Recht auf  Berichtigung, Löschung bzw. Sperrung. Wenden Sie sich hierzu bitte an die im  Impressum angegebene Kontaktadresse. Wir stehen Ihnen jederzeit gern für  weitergehende Fragen zu unseren Hinweisen zum Datenschutz und zur Verarbeitung  Ihrer persönlichen Daten zur Verfügung.<br>
    Unsere Kontaktdaten: Opacak Gruppe, Mario  Opacak und Tomislav Opacak, Hans-Cornelius-Strasse 4, 82166 Gräfelfing,  Deutschland/Germany, Email: <a href="mailto:info@opacak.com">info@opacak.com</a><br>
</p>
